version: '3.1'
services:
  clamav-local-mirror:
    image: ziozzang/clamav-local-mirror
    restart: always
    ports:
      - 8000:8000
  clamav-server:
    image: ziozzang/clamav-server
    restart: always
    ports:
      - 3310:3310
    volumes:
      - ./startup.sh:/opt/startup.sh
    environment:
      CLAMAV_MIRROR: "http://clamav-local-mirror:8000"
